# Generated by Django 5.1.3 on 2025-01-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
