# Generated by Django 5.1.3 on 2024-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=150, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание продукта')),
                ('image', models.ImageField(help_text='Загрузите изображение продукта', upload_to='media/', verbose_name='Фотография')),
                ('category', models.CharField(help_text='Введите название категории', max_length=150, verbose_name='Название категории продукта')),
                ('cost', models.IntegerField(help_text='Введите цену', verbose_name='цена за покупку')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Введите дату последнего обновления', verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'description', 'category', 'cost'],
            },
        ),
    ]
