# Generated by Django 5.1.3 on 2025-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Введите название категории', max_length=150, null=True, verbose_name='Название категории продукта'),
        ),
    ]
